#! /bin/bash

#--------------------------------------------------
# External funtions to include
#--------------------------------------------------

saveIFS=$IFS
IFS=$(echo -e "\n\b")

#--------------------------------------------------
# Set some parameters
export myDate=$(date "+%Y-%m-%d")
export logArchiveDate=$(date -d "14 day ago" +"%s")
export logTarDate=$(date -d "28 day ago" +"%s")
#--------------------------------------------------
sourceAaxFolder=$1
#--------------------------------------------------

IFS=$saveIFS